### ISSUE TITLE
Allow a timezone setting

### ISSUE THREAD

**Issue by R-Jimenez** [Warframe-Community-Developers/genesis#95]
Something I noticed while perusing alerts and playing with the bot (Amazing job, by the way) is that all the timing is in what looks like GMT, and it would be helpful to be able to set an offset or timezone so that I can just glance at the bot's text, instead of looking at the timestamp of the message and calculating from that.

**Comment by aliasfalse** [comment]
The time is always in UTC. The reason we don't do timezone offsets is that in places like public channels, everyone's timezone is gonna be different. it's not really a feasible solution, since it doesn't stop the confusion, it'd only make it different everywhere someone looks.

Feel free to make a note in your channel or to users that times are in UTC and they can add clocks on their machines (windows allows you 2 extra clocks, and I think you can configure something similar on OSX, and can probably do it on linux depending on your flavor.

**Comment by aliasfalse** [comment]
While I agree it'd be nice, the point we're approaching is the tipping point of "is the amount of customization worth the slow-down that having such customization causes"

**Comment by R-Jimenez** [comment]
Makes sense. Consider me satisfied.

**Comment by aliasfalse** [comment]
🙇
